version: 0.1

env:
  variables:
    CONFIG_FILE: config.yml
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python build.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - manifest.zip

